# Generated by Django 3.2.6 on 2021-10-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='was_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
