# Generated by Django 3.2.6 on 2021-10-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introspection', '0003_temporalprimarykey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporalPrimaryKey',
        ),
    ]
