# Generated by Django 3.2.6 on 2021-11-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introspection', '0004_delete_temporalprimarykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='reduction_started',
            field=models.BooleanField(default=False),
        ),
    ]
