# Generated by Django 3.2.6 on 2021-10-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('introspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_process', models.DateTimeField(blank=True, null=True)),
                ('ended_process', models.DateTimeField(blank=True, null=True)),
                ('processed_masking', models.IntegerField(default=0)),
                ('processed_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introspection.table')),
            ],
        ),
    ]
