# Generated by Django 3.2.6 on 2021-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprocess',
            name='processed_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
