# Generated by Django 3.2.6 on 2021-11-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasking', '0002_alter_queueprocess_processed_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueprocess',
            name='reduction_process',
            field=models.TextField(blank=True, default=False),
        ),
    ]
