# Generated by Django 3.2.6 on 2021-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamasking', '0003_queueprocess_reduction_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprocess',
            name='reduction_process',
            field=models.BooleanField(default=False),
        ),
    ]
